const renderKeyboard = () => {
  document.body.innerHTML = '    <h1 class="title">Virtual Keyboard</h1>\n'
        + '    <textarea id="textarea" cols="30" rows="10" class="area__txt" autofocus></textarea>\n'
        + '    <div class="keyboard">\n'
        + '        <div class="line">\n'
        + '            <div class="key symbol" data-name="Backquote">`</div>\n'
        + '            <div class="key symbol" data-name="Digit1">1</div>\n'
        + '            <div class="key symbol" data-name="Digit2">2</div>\n'
        + '            <div class="key symbol" data-name="Digit3">3</div>\n'
        + '            <div class="key symbol" data-name="Digit4">4</div>\n'
        + '            <div class="key symbol" data-name="Digit5">5</div>\n'
        + '            <div class="key symbol" data-name="Digit6">6</div>\n'
        + '            <div class="key symbol" data-name="Digit7">7</div>\n'
        + '            <div class="key symbol" data-name="Digit8">8</div>\n'
        + '            <div class="key symbol" data-name="Digit9">9</div>\n'
        + '            <div class="key symbol" data-name="Digit0">0</div>\n'
        + '            <div class="key symbol" data-name="Minus">-</div>\n'
        + '            <div class="key symbol" data-name="Equal">=</div>\n'
        + '            <div class="key backspace side__btn" data-name="Backspace">Backspace</div>\n'
        + '        </div>\n'
        + '        <div class="line">\n'
        + '            <div class="key tab side__btn" data-name="Tab">Tab</div>\n'
        + '            <div class="key symbol" data-name="KeyQ">q</div>\n'
        + '            <div class="key symbol game__btn" data-name="KeyW">w</div>\n'
        + '            <div class="key symbol" data-name="KeyE">e</div>\n'
        + '            <div class="key symbol" data-name="KeyR">r</div>\n'
        + '            <div class="key symbol" data-name="KeyT">t</div>\n'
        + '            <div class="key symbol" data-name="KeyY">y</div>\n'
        + '            <div class="key symbol" data-name="KeyU">u</div>\n'
        + '            <div class="key symbol" data-name="KeyI">i</div>\n'
        + '            <div class="key symbol" data-name="KeyO">o</div>\n'
        + '            <div class="key symbol" data-name="KeyP">p</div>\n'
        + '            <div class="key symbol" data-name="BracketLeft">[</div>\n'
        + '            <div class="key symbol" data-name="BracketRight">]</div>\n'
        + '            <div class="key symbol" data-name="Backslash">\\</div>\n'
        + '            <div class="key delete side__btn" data-name="Delete">Del</div>\n'
        + '        </div>\n'
        + '        <div class="line">\n'
        + '            <div class="key capslock side__btn" data-name="CapsLock">CapsLock</div>\n'
        + '            <div class="key symbol game__btn" data-name="KeyA">a</div>\n'
        + '            <div class="key symbol game__btn" data-name="KeyS">s</div>\n'
        + '            <div class="key symbol game__btn" data-name="KeyD">d</div>\n'
        + '            <div class="key symbol" data-name="KeyF">f</div>\n'
        + '            <div class="key symbol" data-name="KeyG">g</div>\n'
        + '            <div class="key symbol" data-name="KeyH">h</div>\n'
        + '            <div class="key symbol" data-name="KeyJ">j</div>\n'
        + '            <div class="key symbol" data-name="KeyK">k</div>\n'
        + '            <div class="key symbol" data-name="KeyL">l</div>\n'
        + '            <div class="key symbol" data-name="Semicolon">;</div>\n'
        + '            <div class="key symbol" data-name="Quote">\'</div>\n'
        + '            <div class="key enter side__btn" data-name="Enter">Enter</div>\n'
        + '        </div>\n'
        + '        <div class="line">\n'
        + '            <div class="key lshift side__btn" data-name="ShiftLeft">Shift</div>\n'
        + '            <div class="key symbol" data-name="KeyZ">z</div>\n'
        + '            <div class="key symbol" data-name="KeyX">x</div>\n'
        + '            <div class="key symbol" data-name="KeyC">c</div>\n'
        + '            <div class="key symbol" data-name="KeyV">v</div>\n'
        + '            <div class="key symbol" data-name="KeyB">b</div>\n'
        + '            <div class="key symbol" data-name="KeyN">n</div>\n'
        + '            <div class="key symbol" data-name="KeyM">m</div>\n'
        + '            <div class="key symbol" data-name="Comma">,</div>\n'
        + '            <div class="key symbol" data-name="Period">.</div>\n'
        + '            <div class="key symbol" data-name="Slash">/</div>\n'
        + '            <div class="key side__btn" data-name="ArrowUp">&#9650;</div>\n'
        + '            <div class="key rshift side__btn" data-name="ShiftRight">Shift</div>\n'
        + '        </div>\n'
        + '        <div class="line">\n'
        + '            <div class="key lctrl side__btn" data-name="ControlLeft">Ctrl</div>\n'
        + '            <div class="key side__btn" data-name="MetaLeft"><svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 30 30" width="30px" height="30px"><path d="M12 16L3 16 3 23.75 12 24.988zM12 5L3 6.25 3 14 12 14zM14 4.75L14 14 27 14 27 3zM14 16L14 25.25 27 27 27 16z"/></svg></div>\n'
        + '            <div class="key side__btn" data-name="AltLeft">Alt</div>\n'
        + '            <div class="key space" data-name="Space"> </div>\n'
        + '            <div class="key side__btn" data-name="AltRight">Alt</div>\n'
        + '            <div class="key side__btn" data-name="ArrowLeft">&#9668;</div>\n'
        + '            <div class="key side__btn" data-name="ArrowDown">&#9660;</div>\n'
        + '            <div class="key side__btn" data-name="ArrowRight">&#9658;</div>\n'
        + '            <div class="key rctrl side__btn" data-name="ControlRight">Ctrl</div>\n'
        + '        </div>\n'
        + '    </div>\n'
        + '    <p class="description">Клавиатура выполнена в ОС Windows</p>'
        + '    <p class="description__change__language">Смена языка производится с помощью клавиш Shift + Alt (можно использовать левые и правые клавиши Shift, Alt)</p>';
};

export default renderKeyboard;
